using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace NewsDA.Migrations
{
    public partial class InitialData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Categories",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Categories", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "News",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Title = table.Column<string>(nullable: false),
                    Subtitle = table.Column<string>(nullable: false),
                    Text = table.Column<string>(nullable: false),
                    IsHeaderNews = table.Column<bool>(nullable: false),
                    Imagepath = table.Column<string>(nullable: true),
                    CategoryId = table.Column<int>(nullable: false),
                    CreatedOn = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_News", x => x.Id);
                    table.ForeignKey(
                        name: "FK_News_Categories_CategoryId",
                        column: x => x.CategoryId,
                        principalTable: "Categories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Categories",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "World" },
                    { 2, "Sport" },
                    { 3, "Culture" },
                    { 4, "Life" },
                    { 5, "Tech" },
                    { 6, "Fashion" },
                    { 7, "Politics" },
                    { 8, "Business" }
                });

            migrationBuilder.InsertData(
                table: "News",
                columns: new[] { "Id", "CategoryId", "CreatedOn", "Imagepath", "IsHeaderNews", "Subtitle", "Text", "Title" },
                values: new object[,]
                {
                    { 8, 1, new DateTime(2019, 4, 8, 3, 41, 51, 17, DateTimeKind.Local), null, true, "Incidunt rerum veritatis velit adipisci dicta blanditiis beatae quae sunt dolores.", "Error facilis ad blanditiis. Odit et fuga qui aut aut labore veniam enim. Deleniti dolorem nulla sed soluta quidem eius. Iure aut placeat quam expedita est. Qui voluptas consectetur distinctio exercitationem maxime sed. Est aperiam doloremque occaecati.", "Ut dolor necessitatibus dignissimos adipisci." },
                    { 101, 6, new DateTime(2019, 4, 10, 3, 41, 51, 115, DateTimeKind.Local), null, false, "Eligendi aut minus aliquam eveniet enim est iste.", "Qui repellendus voluptatibus accusamus nam enim. Nostrum maiores quia quo iste eos. Non enim recusandae est et. Quas voluptate sunt est quia expedita ut et. Quo voluptatum minima hic et culpa. Excepturi officia eveniet voluptas cumque voluptatum eaque vel nostrum. Corporis quis harum dolorem aut vel. Maiores sapiente maiores non.", "Corrupti deserunt maiores quibusdam nisi quo." },
                    { 93, 6, new DateTime(2019, 4, 8, 3, 41, 51, 107, DateTimeKind.Local), null, false, "Ea nihil dolores sit omnis et error sequi repellat sunt voluptatem rerum.", "Voluptatem corrupti quas iure. Aliquid consequuntur dignissimos et et. Commodi qui libero libero non sit totam. Neque consequatur eos ullam et qui vitae dolor. Impedit minus aut illo deleniti vitae deleniti similique libero. Illum cupiditate ut ipsam iure.", "Qui itaque eius quia." },
                    { 85, 6, new DateTime(2019, 4, 11, 3, 41, 51, 99, DateTimeKind.Local), null, false, "Reiciendis id veritatis enim aut a et ea enim aliquam quos.", "Id vel voluptatem omnis voluptatem molestiae. Tempora a quo ad nihil. Voluptatem iste ducimus mollitia quisquam et cum tenetur quasi. Dolores et quis commodi. Quia repellat non accusamus voluptatem laborum est ut rerum. Iure aspernatur quis voluptas doloremque ea et. Vel autem quam laborum sapiente voluptatem. Sit sint provident et.", "Error ut suscipit qui." },
                    { 77, 6, new DateTime(2019, 4, 9, 3, 41, 51, 90, DateTimeKind.Local), null, false, "Id accusamus deserunt debitis adipisci occaecati eius voluptas corrupti.", "Sint et placeat consequatur omnis. Similique itaque quia rerum ipsa dolore. Iure et doloremque consectetur dolores totam necessitatibus sunt autem. Eligendi ut quam consectetur quo ut. Laboriosam quia expedita aut consectetur odit vel ut. Quia tempora est natus quaerat illum impedit. Praesentium enim non enim sit ut. Facere consequuntur error illo dolores ea neque minus deserunt.", "Distinctio rerum incidunt aut debitis." },
                    { 69, 6, new DateTime(2019, 4, 7, 3, 41, 51, 82, DateTimeKind.Local), null, false, "Quo laudantium aut sed sint sint animi ut in sequi quis.", "Et quo ullam doloribus quam nemo maiores assumenda aut. Exercitationem molestias non odio earum fuga eius. Et id autem expedita iusto qui. Hic enim reiciendis eius aliquam officiis et. Et at eum veritatis minima rerum quod. Distinctio ea est culpa molestiae sunt.", "Eaque aut unde nulla quidem." },
                    { 61, 6, new DateTime(2019, 4, 10, 3, 41, 51, 75, DateTimeKind.Local), null, false, "Ut animi exercitationem atque neque et illum minima omnis quis.", "Aut voluptatibus culpa recusandae blanditiis aut excepturi. Ut repellat suscipit non et optio. Et nemo consequatur molestias et. Voluptatem perferendis voluptatibus quidem ut rerum beatae et. Dignissimos quae nihil distinctio veniam consequatur aut. Autem sed iure cupiditate molestiae optio est. Quasi id perspiciatis repellat. Consequatur quia veritatis dolorem.", "Doloribus velit exercitationem eaque et harum iure." },
                    { 53, 6, new DateTime(2019, 4, 8, 3, 41, 51, 68, DateTimeKind.Local), null, false, "Id veniam minima sequi ullam esse quis.", "Dolore omnis architecto tempora ducimus reiciendis. Nihil nulla iusto animi beatae totam voluptatem possimus. Velit praesentium eum fugit. Beatae placeat non error maiores voluptate. Est veniam eligendi qui. Commodi dolores molestiae minima suscipit voluptas.", "Expedita culpa eum." },
                    { 45, 6, new DateTime(2019, 4, 11, 3, 41, 51, 61, DateTimeKind.Local), null, false, "Esse quidem vero sequi sed esse fuga sint consequatur architecto beatae officiis.", "Doloribus iusto qui aliquid dolorem. Rerum nisi consequatur expedita natus nostrum delectus quas. Excepturi placeat aliquam consequatur sapiente qui. Neque nostrum ad quibusdam enim et quo assumenda tenetur. Debitis sit est veniam qui sit et exercitationem. Expedita autem quis et commodi ut aliquam voluptatem occaecati. Eum voluptates delectus perspiciatis quia ad. Beatae quis excepturi dignissimos molestias ipsa nihil.", "Repudiandae saepe perferendis deleniti voluptatem ullam." },
                    { 37, 6, new DateTime(2019, 4, 9, 3, 41, 51, 54, DateTimeKind.Local), null, false, "Reiciendis debitis fugit atque vero nostrum sed eius mollitia.", "Ipsa adipisci dicta sed. Sit facilis consequuntur sequi sunt ut. Voluptatem a ut assumenda commodi rerum molestiae quasi. In nemo ipsum ut minus soluta sit voluptas quia. Repellendus enim exercitationem nam consequatur omnis voluptas neque. Minus reprehenderit molestias consequatur deleniti. Neque provident ut magni modi qui corrupti quibusdam beatae. Necessitatibus repudiandae recusandae nam et laudantium.", "Qui laboriosam animi quasi ullam." },
                    { 29, 6, new DateTime(2019, 4, 7, 3, 41, 51, 47, DateTimeKind.Local), null, false, "Quaerat facere illum commodi neque dolor esse est qui.", "Dolor nemo sint sed in. Aliquam ratione magni saepe quia sunt voluptas. In dolorum placeat eius velit debitis vel cupiditate omnis. Facere labore nisi quo. Minus eius adipisci harum voluptatibus doloremque. Ut cumque quia aut soluta. Sint facilis veniam odio nihil. Tenetur libero expedita fugit reiciendis temporibus.", "Voluptatibus itaque eos itaque et ad quae." },
                    { 21, 6, new DateTime(2019, 4, 10, 3, 41, 51, 39, DateTimeKind.Local), null, false, "Eligendi quo et deserunt nihil officiis officia est suscipit.", "Consequatur et hic odio sint. Et distinctio exercitationem provident deleniti veritatis consequatur nam. Nostrum et ut sequi est. Est velit beatae pariatur et dignissimos deserunt laborum voluptas. Voluptatem adipisci architecto occaecati eos molestiae et. Saepe at aut aspernatur quia. Quo provident eligendi dicta earum blanditiis.", "Ab non repudiandae sit accusamus non." },
                    { 13, 6, new DateTime(2019, 4, 8, 3, 41, 51, 33, DateTimeKind.Local), null, false, "Voluptas quo dolorem laborum rerum unde dolor nemo.", "Deleniti sapiente quas quis quia modi dolorem. Alias quis iste consectetur est voluptatem adipisci aut. Quia veritatis in cum. Aperiam inventore et fugit rerum inventore aut quia. Repudiandae facilis excepturi aut odio unde porro repellat. Voluptatibus quis eos delectus consequatur sed qui. Et at iure quis. Iste et impedit non dignissimos possimus quia.", "Sit voluptatem quia unde esse corporis harum." },
                    { 109, 6, new DateTime(2019, 4, 7, 3, 41, 51, 121, DateTimeKind.Local), null, false, "Molestiae fuga excepturi veritatis provident illo perspiciatis qui voluptatum voluptatem animi.", "Corporis dolore dicta voluptas alias unde quos. Necessitatibus qui enim voluptatem reprehenderit praesentium iusto. Expedita qui molestiae molestiae. Qui vitae amet nemo dolores alias et. Corrupti non recusandae vitae dolorum aperiam vel deserunt deserunt. Quis rerum ratione et qui officia quae rerum molestias. Praesentium incidunt tempora et sunt ipsa et dolorem. Provident et perspiciatis eligendi facere in numquam laboriosam labore.", "Magnam dolores ipsa voluptate." },
                    { 5, 6, new DateTime(2019, 4, 11, 3, 41, 51, 14, DateTimeKind.Local), null, false, "Et dicta quisquam provident ea voluptatem et et eaque.", "Et voluptatem iste temporibus dolores temporibus nobis sint delectus. Totam et nulla voluptatem aut est nesciunt dolorem vitae. Vel beatae corrupti adipisci non suscipit aut facilis. Harum eum at est assumenda et rerum. Facere mollitia adipisci qui neque. Et sunt ratione et. Modi eius quidem repellendus.", "Suscipit provident laborum enim." },
                    { 108, 5, new DateTime(2019, 4, 8, 3, 41, 51, 120, DateTimeKind.Local), null, false, "Et et et autem assumenda consequatur delectus vero consequatur ad ut.", "Voluptas officiis voluptas est. Aut aut ea et ut molestias. Magni sint velit occaecati corrupti. Voluptatem optio voluptatem in. Quibusdam dolores repellendus dicta quaerat ut et. Quia quae quae tempore voluptate. Asperiores iusto autem omnis doloribus beatae quia suscipit inventore.", "Error rerum fuga inventore." },
                    { 100, 5, new DateTime(2019, 4, 11, 3, 41, 51, 114, DateTimeKind.Local), null, false, "Eaque velit voluptas accusantium itaque consequuntur ut odio unde error.", "Labore optio cumque tempora earum. Dolorem ut id id dolorem exercitationem. Perferendis omnis commodi corporis qui facilis deserunt aut. Quaerat voluptatem nam aut reprehenderit. Et aut ut et molestias. Ratione explicabo sunt aut provident expedita totam ad quo. Aut minus dolores praesentium.", "Earum doloribus asperiores." },
                    { 92, 5, new DateTime(2019, 4, 9, 3, 41, 51, 106, DateTimeKind.Local), null, false, "Fugit quas inventore quia mollitia quia debitis ea possimus nostrum id.", "Dignissimos quisquam quae sint repudiandae. Ducimus et eius id sunt possimus nisi dolorem qui. Aut architecto vero voluptatem dolores. Numquam quis dolor quibusdam blanditiis reprehenderit quia fuga. Numquam qui qui provident quia exercitationem aspernatur. Ipsum est cumque molestiae deserunt qui cupiditate voluptas et. Qui ut enim et enim qui et quas possimus.", "Repellendus tempora est molestiae et saepe fuga nihil." },
                    { 84, 5, new DateTime(2019, 4, 7, 3, 41, 51, 98, DateTimeKind.Local), null, false, "Doloribus quasi sint debitis dolore quidem aut.", "Iste molestiae aspernatur voluptate excepturi delectus. Iusto rerum quidem sed. Repellat dolores ducimus nesciunt voluptatem veritatis quia. Cum provident alias ut. Iste aliquam et perferendis beatae. Facilis ratione ea velit non atque.", "Iste ipsa recusandae." },
                    { 76, 5, new DateTime(2019, 4, 10, 3, 41, 51, 89, DateTimeKind.Local), null, false, "Ut ullam aut doloremque natus porro molestiae voluptatum quibusdam fuga assumenda sed.", "Iure quis quam minus quia. Fugit dolorem officia excepturi eos minima earum. Aut sequi corporis quidem vel placeat totam ut iste. Voluptate quo soluta sunt non deleniti atque ullam. Sint reprehenderit corporis non sed iusto tenetur. Ratione et expedita deserunt et natus earum nobis. Natus natus omnis adipisci quod. Minus officia voluptas quos.", "A voluptatem pariatur eveniet labore et voluptatem id." },
                    { 68, 5, new DateTime(2019, 4, 8, 3, 41, 51, 81, DateTimeKind.Local), null, false, "Nam ea enim corporis ab voluptatum molestiae quas quis officiis recusandae.", "Porro neque exercitationem totam. Dicta iste ipsam unde officiis maxime et beatae. Officiis mollitia quia provident eius est maiores. Tempore sint numquam aut neque quisquam. Iste blanditiis iusto harum. Atque commodi corporis illum id.", "Dolorem et dicta tempora corrupti vel." },
                    { 60, 5, new DateTime(2019, 4, 11, 3, 41, 51, 74, DateTimeKind.Local), null, false, "Qui magnam sunt maiores laudantium officia eum et ut a sit eligendi.", "Ullam ut est voluptatem. Ipsam quis est unde quo. Debitis iusto delectus eos. Numquam aliquid et repellendus quis. Eveniet quo et iste est deleniti. Delectus et eligendi architecto molestiae provident sapiente quaerat.", "Enim quisquam iusto nulla sint laboriosam vel eum." },
                    { 52, 5, new DateTime(2019, 4, 9, 3, 41, 51, 67, DateTimeKind.Local), null, false, "Sed aliquid error nostrum sit perspiciatis doloribus quia deserunt.", "Ipsam aspernatur quia aliquid ipsum esse eum quia aliquam. Error temporibus officiis inventore ad veritatis distinctio illo doloremque. Autem tenetur temporibus sunt. Est eligendi ducimus sed ut. Ad assumenda sit quasi sequi. Omnis natus consectetur cumque sapiente ea. Placeat pariatur expedita sit velit laboriosam eum inventore. Temporibus non commodi enim aperiam neque deleniti est.", "Dolores quo vel esse deserunt accusantium nisi nisi." },
                    { 44, 5, new DateTime(2019, 4, 7, 3, 41, 51, 60, DateTimeKind.Local), null, false, "Quibusdam architecto ut alias animi earum amet et accusamus omnis praesentium.", "Harum aut aut numquam qui consectetur ipsum placeat odio. Laborum omnis et est animi autem alias praesentium sed. Veniam fugiat consequatur et non. Dolore voluptatibus aspernatur similique qui sequi qui iusto. Rerum et qui rem. Deleniti non nam doloremque. Accusamus maiores deserunt nihil aut animi quidem porro numquam.", "Eius quidem porro." },
                    { 36, 5, new DateTime(2019, 4, 10, 3, 41, 51, 53, DateTimeKind.Local), null, false, "Delectus natus et autem occaecati distinctio in eum repellendus enim.", "Ad modi consequatur quia rerum enim in. Maiores possimus dolorem neque ut. Et similique sapiente ipsam culpa. Architecto quidem aliquam dignissimos quas. Autem sint harum id ut. Libero praesentium voluptate sit sed quae ducimus. Ut aut omnis illo quae ipsum dolorum. Voluptas veritatis nihil dolor commodi impedit natus.", "Odio ut officia consequatur sint." },
                    { 28, 5, new DateTime(2019, 4, 8, 3, 41, 51, 46, DateTimeKind.Local), null, false, "Voluptatem illum in dolores recusandae iure quae ut blanditiis aut.", "Aut aut tempore magnam dolor placeat neque. Id eligendi voluptas impedit. Et enim voluptatibus consequatur aut et. Reprehenderit ipsum delectus quia. Deleniti atque aliquid in rem debitis amet non dignissimos. Voluptatem dignissimos unde officiis odit dolor eaque rerum error. Optio consequatur velit sunt explicabo iste omnis repellendus. Consectetur quo dolores omnis quis corporis ut vel.", "Ut ex quis ea sit dolor." },
                    { 20, 5, new DateTime(2019, 4, 11, 3, 41, 51, 39, DateTimeKind.Local), null, false, "Quis rerum voluptas vel officiis eligendi tempore aspernatur harum reprehenderit expedita.", "Eos suscipit voluptatem sit mollitia. Et nisi ut consectetur perferendis tempore iure et provident. Aut et a culpa ipsum quas rerum dolores. Illum autem omnis aut libero corporis. Dolorem dolorem et neque at non fuga. Et molestiae voluptas et delectus repellat.", "Omnis sed ex sit incidunt rerum aliquid pariatur." },
                    { 116, 5, new DateTime(2019, 4, 10, 3, 41, 51, 126, DateTimeKind.Local), null, false, "Et error repudiandae qui quasi dolores quis maiores itaque explicabo.", "Est omnis provident non. Consequatur reprehenderit ut velit. Et quam ut deleniti aut minima eligendi. Veritatis ullam explicabo dolorem deleniti in nesciunt. Et exercitationem quo consequuntur. Vitae facere occaecati eaque dolores amet. In in est sunt. Iure fugit sint non voluptatem velit optio unde.", "Quis velit dolorem." },
                    { 12, 5, new DateTime(2019, 4, 9, 3, 41, 51, 32, DateTimeKind.Local), null, false, "Id consequatur consectetur eos aliquam commodi qui quam.", "Ut aut expedita reiciendis aut dolor sit hic. Maxime impedit esse sint velit labore vero libero natus. Vel neque ducimus reprehenderit. Molestiae quo vero mollitia qui. Id blanditiis ab temporibus dolor consequatur mollitia. Magni non quibusdam quia et voluptates quis quam nisi. Quis voluptatem quo id dolorem dolores animi. Quos ea illo sunt.", "Quaerat id molestiae quos qui." },
                    { 117, 6, new DateTime(2019, 4, 9, 3, 41, 51, 126, DateTimeKind.Local), null, false, "Nulla quia perferendis perspiciatis ut asperiores quibusdam ducimus incidunt.", "Odio reiciendis explicabo id non atque est occaecati. Sunt veniam facilis voluptates. Aspernatur eos culpa possimus. Amet est numquam veritatis ab quo deserunt rerum excepturi. Et consectetur nostrum nulla laudantium aut eius. Earum expedita possimus officiis reprehenderit dolor voluptatibus. Qui beatae dolorem repellat molestiae nihil dignissimos doloribus deleniti. Modi sint ipsa necessitatibus.", "Provident quidem aspernatur beatae ipsam numquam iusto beatae." },
                    { 14, 7, new DateTime(2019, 4, 7, 3, 41, 51, 34, DateTimeKind.Local), null, false, "Velit facilis quia porro vitae explicabo fugiat doloremque.", "Beatae eum fugiat asperiores magnam. Iure reprehenderit dicta id ullam excepturi aut sapiente. Incidunt eius expedita enim aliquid dolorem maiores omnis. Enim cupiditate et vitae aut eos id architecto. Velit cum qui dignissimos assumenda laudantium eaque tempora magnam. Sunt consequatur labore tempora ea esse.", "Est quisquam nemo esse rerum alias modi." },
                    { 103, 8, new DateTime(2019, 4, 8, 3, 41, 51, 116, DateTimeKind.Local), null, false, "Iste veritatis eum culpa dolorem voluptas ut hic molestiae ullam.", "Molestiae consequuntur ab facere. Veniam molestiae delectus incidunt rem quibusdam magnam sed laborum. Dolorem sit dolor ea deleniti numquam. Sapiente quis corrupti voluptatem vero magni reiciendis sed quia. Repellendus cupiditate consequuntur ad deserunt ipsa accusantium delectus. Atque mollitia mollitia eum. Qui voluptatibus commodi repellendus occaecati.", "Aut ullam odit totam soluta atque inventore in." },
                    { 95, 8, new DateTime(2019, 4, 11, 3, 41, 51, 109, DateTimeKind.Local), null, false, "Dicta quos modi blanditiis quia qui incidunt dignissimos rem explicabo.", "Atque minus voluptas quam facere minus tempora labore. Qui praesentium quas veritatis aliquid. Suscipit facere et non et qui ipsa voluptatem ut. Ad culpa qui maiores amet modi mollitia vel laboriosam. Ut est omnis quia enim dolor. Ad eos eos numquam impedit.", "Voluptatum voluptatem est aliquam aperiam." },
                    { 87, 8, new DateTime(2019, 4, 9, 3, 41, 51, 101, DateTimeKind.Local), null, false, "Ut possimus distinctio tempora alias sint provident omnis asperiores accusamus.", "Iste id aut illum sapiente aliquam voluptatem voluptatem. Quis aut delectus harum accusamus. Libero corporis ea esse doloremque cupiditate omnis. Voluptatum illo delectus eum. Officiis cumque debitis consequuntur. Et nihil voluptas enim accusamus qui. Modi vel nam magni. Vel rem molestias et vel.", "Minima omnis voluptate." },
                    { 79, 8, new DateTime(2019, 4, 7, 3, 41, 51, 93, DateTimeKind.Local), null, false, "Vel omnis aut sit quas officiis consequatur officia quidem.", "Consectetur itaque magni est sed nulla sit non ipsum. Voluptas perferendis dolore sed. Ut aliquid enim vel. Reiciendis id corporis sapiente eveniet officiis. Voluptatem accusamus voluptas voluptatem. Vitae rerum numquam velit suscipit ipsa est quia. Blanditiis nesciunt minima voluptas veritatis suscipit.", "Officiis distinctio eum aut." },
                    { 71, 8, new DateTime(2019, 4, 10, 3, 41, 51, 83, DateTimeKind.Local), null, false, "Eius et totam maiores sunt architecto recusandae nihil.", "Assumenda animi eligendi cupiditate aliquid quo. Ea libero vero quia. Sit omnis ratione sunt. Ipsam qui quia numquam id quia tenetur aliquam. Culpa alias ratione voluptates magnam. Error ut et veniam.", "Rerum consequuntur quia nihil alias suscipit corporis." },
                    { 63, 8, new DateTime(2019, 4, 8, 3, 41, 51, 77, DateTimeKind.Local), null, false, "Distinctio et minus aliquam voluptatem odit rerum dolorem ducimus voluptates doloremque.", "Delectus exercitationem dolorem in quis. Numquam praesentium autem natus magnam optio eum. Harum nemo optio inventore. Laudantium tempora et pariatur sint perspiciatis doloribus. Vitae iusto et corrupti ab. Voluptatum ullam molestiae facere nobis laborum. Voluptatum qui assumenda et et dicta debitis.", "Blanditiis magni accusantium exercitationem." },
                    { 55, 8, new DateTime(2019, 4, 11, 3, 41, 51, 69, DateTimeKind.Local), null, false, "Nihil architecto provident explicabo voluptatum nihil et.", "Dolor fugit commodi ut. Magni laboriosam atque unde qui asperiores. Officia a fuga sequi provident dolore. Laborum est voluptatum quae est excepturi expedita reprehenderit. Dolor voluptatem ea sed magnam. Quaerat in sequi dolores possimus. In fuga iure necessitatibus. Consequatur harum reiciendis ut.", "Quo vel quod vitae cumque cupiditate sit." },
                    { 47, 8, new DateTime(2019, 4, 9, 3, 41, 51, 63, DateTimeKind.Local), null, false, "Qui ea quaerat temporibus nobis facilis voluptas rem dolores qui.", "Unde porro odit ut velit at. Ex enim dolores voluptas expedita unde provident pariatur provident. Quasi officia odio earum sapiente. Nulla dolor sint non omnis. Omnis ex velit quod atque assumenda voluptas quas doloremque. Molestiae velit adipisci est sint quia inventore eveniet aut. Adipisci necessitatibus qui consequatur modi.", "Repudiandae et voluptas vitae accusantium modi dolor distinctio." },
                    { 39, 8, new DateTime(2019, 4, 7, 3, 41, 51, 56, DateTimeKind.Local), null, false, "Aut cum fuga omnis at omnis nesciunt ad impedit qui omnis.", "Unde ut nam ratione rerum. Eos minima quo iure et. Esse et saepe dolorem animi amet alias optio sed. Sint ut nostrum ipsum ipsum officia sunt iure et. Aperiam a est modi id. Est qui laudantium et fugit libero fugiat earum. Quas veniam culpa cupiditate quaerat corporis.", "Dolorem blanditiis dolores libero modi nulla." },
                    { 31, 8, new DateTime(2019, 4, 10, 3, 41, 51, 49, DateTimeKind.Local), null, false, "Corporis voluptas minus ab placeat quia molestiae facilis quo quia.", "Sint vel est provident doloribus commodi totam eaque laudantium. Et sed id sed quis. Officia qui unde sed voluptate sed. Dolores ut ea est eveniet eaque. Expedita fugiat similique voluptates deleniti. Earum soluta perspiciatis id pariatur.", "Aut provident voluptatibus ea consectetur voluptatem." },
                    { 23, 8, new DateTime(2019, 4, 8, 3, 41, 51, 41, DateTimeKind.Local), null, false, "Officiis voluptatem consequatur iste exercitationem exercitationem explicabo sed amet.", "Aut et libero nostrum est sed et officia vero. Voluptatem reprehenderit aut consequatur non reprehenderit iure. Aut inventore ut ex provident. Sit enim sit deleniti. Ullam ex qui ullam similique illum omnis dolores. Laudantium vel ut autem. Accusantium pariatur sed amet numquam eligendi. Assumenda eveniet minus est et placeat sit et a.", "Saepe modi accusamus deserunt impedit placeat asperiores." },
                    { 15, 8, new DateTime(2019, 4, 11, 3, 41, 51, 35, DateTimeKind.Local), null, false, "Autem cumque voluptatibus quis ea blanditiis tenetur sed beatae aut.", "Quis ut repellendus ducimus adipisci enim consequuntur repudiandae cupiditate. Autem quasi exercitationem impedit libero distinctio itaque a facere. Fugit qui doloribus velit. Quod voluptatem et quo. Sunt dolor deserunt voluptatem architecto dignissimos non. Qui ab officia dolorem similique at labore est. Aut rerum possimus consequatur ipsa rem.", "Perferendis deleniti reiciendis quidem modi." },
                    { 6, 7, new DateTime(2019, 4, 10, 3, 41, 51, 15, DateTimeKind.Local), null, false, "Debitis quo sequi et a suscipit recusandae dolores.", "Accusantium voluptate voluptate similique rerum sunt est. Fuga odit eum sunt. Nihil quis repellat animi deleniti qui nobis non. Aut quos autem quis perspiciatis fugiat. Sit voluptatum officiis ipsum praesentium adipisci consequatur incidunt. Corrupti eum iusto cumque voluptates.", "Reprehenderit id et non repudiandae est." },
                    { 7, 8, new DateTime(2019, 4, 9, 3, 41, 51, 16, DateTimeKind.Local), null, false, "Facilis qui quas fugit eveniet corporis eligendi.", "Vel exercitationem nostrum harum molestias sint nostrum. Natus assumenda eum asperiores eveniet. Incidunt et et laborum beatae. Molestiae debitis reprehenderit in. Voluptas dolor est culpa veniam ipsam. Rerum minima fuga voluptate dolorum dolorum. Quibusdam eos reprehenderit qui error omnis.", "Fuga recusandae et saepe nostrum." },
                    { 110, 7, new DateTime(2019, 4, 11, 3, 41, 51, 122, DateTimeKind.Local), null, false, "Tempora aliquid repellat tenetur expedita aliquid blanditiis dolores esse et.", "Corporis excepturi in consequuntur est eligendi inventore asperiores. Consectetur qui occaecati est magnam aut fugit beatae. Hic dolorem optio in. Facilis et ut corporis. Et ab et nisi eos. Aperiam est consectetur corporis reiciendis illum consequatur.", "Sunt consequatur qui atque non." },
                    { 102, 7, new DateTime(2019, 4, 9, 3, 41, 51, 116, DateTimeKind.Local), null, false, "Dolore perspiciatis ducimus dolorem et et ducimus.", "Accusantium consequatur omnis et. Aliquid dolorem est similique nihil explicabo sequi sapiente. Deserunt id aliquam eveniet rerum aperiam ducimus culpa. Dolorem id consequatur vel dolor est accusantium nam. Accusantium repudiandae recusandae dolorum qui dolorem recusandae expedita. Est voluptas error omnis ea rerum quibusdam.", "Mollitia optio tenetur sed iure a." },
                    { 94, 7, new DateTime(2019, 4, 7, 3, 41, 51, 108, DateTimeKind.Local), null, false, "Voluptatem repudiandae quidem sit velit non alias consequatur molestiae dolores officia mollitia.", "Ipsum id atque aut est consectetur aspernatur vero. Est sit non eligendi. Enim natus accusantium qui nesciunt vitae et ipsum. Illo iure inventore deserunt vel dicta ut animi. Tenetur qui numquam magnam debitis ut. Eum nam ab odio quas illum neque sit dolores.", "Est vero ab eum aut odit sed." },
                    { 86, 7, new DateTime(2019, 4, 10, 3, 41, 51, 100, DateTimeKind.Local), null, false, "Quia nobis repellendus autem quis delectus repudiandae quam nesciunt.", "Eaque est aliquam nisi. Doloribus molestias excepturi eaque saepe vero delectus explicabo labore. Sed est est eaque. Quod architecto vero quo. Consequuntur rerum magni quae doloribus. Consectetur autem ea quos totam excepturi quidem fugiat architecto. Officia et est unde corporis nesciunt magnam voluptatem.", "Odit vel laudantium quae et libero quia." },
                    { 78, 7, new DateTime(2019, 4, 8, 3, 41, 51, 92, DateTimeKind.Local), null, false, "Illum qui ab autem maiores voluptas ex ipsum beatae.", "Qui error eos occaecati quia et distinctio eius et. Omnis numquam nostrum a dolores explicabo dolor. Hic sed mollitia voluptatem placeat asperiores totam. Et suscipit et saepe laudantium quia est. Iusto dolorem blanditiis eos veniam sapiente. Expedita magni reiciendis blanditiis fuga velit reprehenderit dolorem temporibus. Ducimus non ea aliquid.", "Est debitis occaecati voluptas rerum ipsam." },
                    { 70, 7, new DateTime(2019, 4, 11, 3, 41, 51, 83, DateTimeKind.Local), null, false, "Quos quod temporibus animi aut delectus ut.", "Corporis qui fugit natus earum corrupti consequuntur dolore quo. Distinctio natus adipisci autem perspiciatis. Possimus dolore facere voluptate quae. Officia molestiae voluptates voluptates. Nihil deleniti aut iste dolores non. Enim qui mollitia ut quasi harum. Ut rerum sit quod deserunt dolor.", "Repellat nobis et aperiam." },
                    { 62, 7, new DateTime(2019, 4, 9, 3, 41, 51, 76, DateTimeKind.Local), null, false, "Est repudiandae natus molestiae nesciunt dolor quaerat possimus.", "Quisquam voluptatem sit sunt ut. Sed dolorum deserunt quidem est ea fugiat et aperiam. Ea necessitatibus a tenetur impedit. Qui commodi ad beatae. Dolore a vel quia recusandae. Qui recusandae et ut est culpa quaerat eveniet.", "Quod et enim sed." },
                    { 54, 7, new DateTime(2019, 4, 7, 3, 41, 51, 68, DateTimeKind.Local), null, false, "Quis odio excepturi sint nulla modi labore quod odit recusandae rem aspernatur.", "Sint sit ipsum doloremque qui nam praesentium. Eligendi recusandae natus maxime dolor et aut. Sit qui eos dolorum temporibus. Inventore et deserunt harum ratione et. Blanditiis consectetur qui consequatur nemo provident. Sapiente qui dolores tempore vel totam. Aliquid porro velit sint. Ut debitis quia at ut voluptatem est sed.", "Modi recusandae deserunt amet labore voluptatem suscipit." },
                    { 46, 7, new DateTime(2019, 4, 10, 3, 41, 51, 62, DateTimeKind.Local), null, false, "Laborum alias sunt omnis quis unde a aut ducimus.", "Repudiandae repellendus cupiditate aut et aliquam quaerat repellendus. Voluptatem facere qui est hic ut qui. In illo omnis reprehenderit sapiente rem ipsa in eos. Deleniti dolores delectus consectetur. Dolores inventore et pariatur sit qui aliquam neque. Qui quos et voluptas nostrum saepe. Fuga et est sint dolore consequatur ea tenetur ipsam.", "Ducimus esse et est qui saepe qui." },
                    { 38, 7, new DateTime(2019, 4, 8, 3, 41, 51, 55, DateTimeKind.Local), null, false, "Ut et quidem est voluptas impedit hic illo quod et necessitatibus.", "Sunt ratione rerum quidem tenetur. Exercitationem excepturi numquam velit voluptatum quidem fugiat et harum. Doloremque non consequuntur consequatur excepturi. Labore consequatur voluptates fuga aliquam. Praesentium voluptatum in officia tempora expedita. Molestias qui est accusantium. Illum ut rerum explicabo inventore culpa voluptas reiciendis excepturi. Similique ut ipsum voluptatem.", "Quia voluptate consequuntur dignissimos corporis." },
                    { 30, 7, new DateTime(2019, 4, 11, 3, 41, 51, 48, DateTimeKind.Local), null, false, "Delectus voluptatem similique voluptas explicabo ut dolorem atque quod quo.", "Velit in id voluptates illum. Provident delectus aut possimus beatae. Numquam voluptas excepturi est. Provident suscipit perferendis quibusdam voluptatem sint cupiditate. Corporis et nulla iusto necessitatibus reprehenderit est quasi facere. Saepe et nulla repellat ab et non.", "Molestiae itaque veritatis." },
                    { 22, 7, new DateTime(2019, 4, 9, 3, 41, 51, 40, DateTimeKind.Local), null, false, "Et et neque blanditiis ut qui ratione vel numquam cum.", "Eos repellat quibusdam voluptatem accusamus saepe. Architecto impedit dolores autem facere quas libero enim. Blanditiis ea rerum molestiae nesciunt. Nulla similique iste sed et sunt non. Nulla animi unde nihil. Blanditiis qui et delectus.", "Excepturi nostrum eius modi corporis sequi tempora nihil." },
                    { 118, 7, new DateTime(2019, 4, 8, 3, 41, 51, 127, DateTimeKind.Local), null, false, "Sunt ut qui dolor dolorem et quo adipisci alias nisi.", "Sint vel sint culpa autem maxime ullam consequatur quia. Corporis error ab voluptatem repudiandae cumque vel. Beatae vero recusandae et mollitia. Qui quasi nisi voluptates. Et temporibus quo voluptas. Qui aperiam expedita et placeat sequi eligendi molestiae quia.", "Rerum eius in." },
                    { 111, 8, new DateTime(2019, 4, 10, 3, 41, 51, 122, DateTimeKind.Local), null, false, "Quia sit qui voluptates quo nam dolorem molestiae nihil rerum asperiores.", "Reprehenderit repellendus vel omnis sed illo vel sunt. Vitae molestiae omnis nesciunt magni. Sequi ut cum facilis. Dolore tenetur illum deleniti harum placeat. Ab molestias corporis et quaerat laborum incidunt nihil eius. Qui illum rerum sunt. Dolores autem non rerum placeat sit non. Vel consequatur veniam numquam dolores odio ut eveniet qui.", "Eos cumque et nobis illum odio ut doloribus." },
                    { 4, 5, new DateTime(2019, 4, 7, 3, 41, 51, 13, DateTimeKind.Local), null, false, "Ut minus voluptatibus ut beatae accusantium repellendus iste et sunt ducimus.", "Qui nihil eaque suscipit ut animi eius eos. Quos pariatur occaecati sed temporibus. Ullam enim eum natus fugit cupiditate quis qui aliquam. Dolorem excepturi est earum ducimus cumque eveniet et. Necessitatibus odit ad facere mollitia nihil voluptas voluptas blanditiis. Suscipit enim et libero qui ut.", "Accusamus autem hic blanditiis." },
                    { 107, 4, new DateTime(2019, 4, 9, 3, 41, 51, 120, DateTimeKind.Local), null, false, "Veniam id soluta repellendus ut iusto qui debitis aut.", "Qui ut ratione harum commodi aut ut ut optio. Libero soluta autem dolor. Culpa voluptate ut hic. Esse consectetur totam eaque. Consequatur ullam tenetur eligendi aliquam ipsum voluptas est. Distinctio minima impedit facilis. Mollitia aperiam provident temporibus libero eos minima impedit dolorem.", "Ex consequatur rerum ad odio et dolorem quasi." },
                    { 97, 2, new DateTime(2019, 4, 9, 3, 41, 51, 111, DateTimeKind.Local), null, false, "Quam eos autem velit vero rerum at qui mollitia.", "Qui sit non quae qui quia in dolores. Facilis quisquam autem necessitatibus quidem qui. Commodi mollitia error temporibus ipsa. Dolorem ipsum fuga soluta fugiat autem rerum. Autem in velit iste et harum. Voluptatem dolor sed suscipit. Quasi sed ut earum nihil inventore totam. Enim blanditiis odit doloribus repellendus at dolorem.", "Qui excepturi dolorem laboriosam." },
                    { 89, 2, new DateTime(2019, 4, 7, 3, 41, 51, 103, DateTimeKind.Local), null, false, "Molestiae consequuntur veritatis distinctio necessitatibus autem sit repellat nemo odit excepturi.", "Voluptates tenetur possimus officia voluptas ducimus officia voluptas magnam. Maxime expedita molestiae eos fuga deleniti. Libero odio nulla recusandae esse ut nisi suscipit quia. Deserunt nisi rem et ipsam non et. Minus aut accusamus libero dolores id. Autem consectetur molestiae quia nemo perspiciatis. Soluta rerum atque doloremque vitae. Quos porro velit aliquam dignissimos quibusdam repellat maiores dolor.", "Quae sint numquam perferendis odit quis." },
                    { 81, 2, new DateTime(2019, 4, 10, 3, 41, 51, 95, DateTimeKind.Local), null, false, "Enim magnam quam illo ullam fugiat magni inventore rerum soluta.", "Et nam velit nihil quas consectetur nisi in. Sit laboriosam commodi blanditiis atque. Harum magni eum nesciunt. Blanditiis commodi dolore ex ea libero inventore quis qui. Aut libero aliquam facere cupiditate hic quia. Et doloremque nesciunt earum quaerat. Non ea et debitis porro fugiat aut et et.", "Libero odit cumque sapiente." },
                    { 73, 2, new DateTime(2019, 4, 8, 3, 41, 51, 85, DateTimeKind.Local), null, false, "Et consequatur fugiat temporibus omnis incidunt aperiam quis sit qui qui saepe.", "Nam cupiditate earum non qui exercitationem aliquid veritatis et. Ea animi fuga perspiciatis vel. Eligendi voluptate soluta odit aut autem ipsum. Et nam exercitationem totam harum. Praesentium laborum ab reprehenderit excepturi aut quia odit a. Perferendis eum delectus atque ea vitae mollitia asperiores. Ipsa quo sit id optio facere. Aliquid est minima repellendus alias.", "Minima velit nobis." },
                    { 65, 2, new DateTime(2019, 4, 11, 3, 41, 51, 79, DateTimeKind.Local), null, false, "Soluta deserunt ducimus tempora ipsum ea soluta nesciunt voluptatum dolorem.", "Autem culpa tempora impedit. Magni necessitatibus facilis ut natus amet. Cumque qui iusto delectus consequuntur. Nihil reiciendis dolores ea. Excepturi hic beatae magni. Harum ea rerum a.", "Minima deserunt accusamus ipsa iste maxime." },
                    { 57, 2, new DateTime(2019, 4, 9, 3, 41, 51, 72, DateTimeKind.Local), null, false, "Qui amet inventore at ad id explicabo quod debitis ut eligendi non.", "Nesciunt ipsa non aut expedita at dolor dolore pariatur. At excepturi nostrum ipsa. Doloribus et iure praesentium consequatur omnis aspernatur. Magnam ut natus fugit corporis. Nesciunt sed rem consequuntur esse iure minima commodi. Similique mollitia aspernatur libero. Alias est quia ex cumque nemo veniam saepe omnis.", "Iure debitis et labore et." },
                    { 49, 2, new DateTime(2019, 4, 7, 3, 41, 51, 64, DateTimeKind.Local), null, false, "Optio sunt nihil et officia soluta aut officiis.", "Non sed occaecati numquam necessitatibus praesentium sit dolor. Omnis impedit sunt ratione delectus sunt itaque culpa voluptas. Placeat quisquam sed velit iure est libero voluptas labore. Modi quia accusantium eligendi enim odit temporibus voluptatem. Porro nulla veritatis recusandae nihil sapiente. Voluptate dolorem esse vero. Quas nam est incidunt. Cum autem dolores cupiditate.", "Ullam cum amet quae inventore nobis temporibus fugiat." },
                    { 41, 2, new DateTime(2019, 4, 10, 3, 41, 51, 58, DateTimeKind.Local), null, false, "Voluptatem distinctio dignissimos iusto itaque consequuntur molestias nisi sit suscipit magni molestiae.", "Architecto occaecati excepturi sint. Sit perspiciatis aut id quia voluptas cupiditate. Eum eaque vel ut in. Minima vitae ea dolor velit. Et et pariatur ut perspiciatis possimus et eum aperiam. Qui consequatur quisquam quia.", "Earum non tempore id aspernatur sunt." },
                    { 33, 2, new DateTime(2019, 4, 8, 3, 41, 51, 51, DateTimeKind.Local), null, false, "Aut voluptate sunt quisquam nihil optio est et tempora quis fugit sed.", "Quasi ipsam consequatur porro id quis. Adipisci iste nihil facere. Est facere doloribus quia. Accusantium dolorum quia non sint aut. Facilis rem mollitia neque quas odio. Sint blanditiis enim cum cupiditate et voluptas adipisci.", "Eveniet esse iste numquam ipsam." },
                    { 25, 2, new DateTime(2019, 4, 11, 3, 41, 51, 43, DateTimeKind.Local), null, false, "Qui ea rerum molestias in eius sit enim.", "Nulla doloribus et vero temporibus qui ipsam id consequatur. Distinctio placeat dolores aperiam repellendus saepe. Et magnam et officia sed. Nesciunt ab eius sint error ab nihil. Accusamus libero libero aut aperiam ea dignissimos. Hic et minus sunt unde non laboriosam.", "Blanditiis ad consequatur sunt provident placeat omnis." },
                    { 17, 2, new DateTime(2019, 4, 9, 3, 41, 51, 36, DateTimeKind.Local), null, false, "Assumenda in qui perferendis ad expedita voluptatem cumque.", "Dolorem vero laudantium nobis hic ut vero. Accusamus blanditiis nobis asperiores ut eos soluta est et. Sint at blanditiis totam explicabo ab in cupiditate minus. Odit expedita et doloremque. Dolorem dolor doloribus modi. Dolore provident quis impedit. Ut qui debitis nesciunt.", "Velit aut molestiae et at eum non." },
                    { 9, 2, new DateTime(2019, 4, 7, 3, 41, 51, 18, DateTimeKind.Local), null, false, "Modi magni ab qui qui officia sed.", "Itaque voluptatem voluptatem nobis quae fuga aut temporibus ea. Ut dolorem et sed sed ut et hic. Modi similique incidunt nihil nobis ut. Neque hic similique incidunt nam esse ut et. Commodi vitae sed perferendis temporibus modi exercitationem. Commodi consequatur et voluptas. Consequatur earum iure dolores vero laudantium. Nihil saepe totam ducimus aliquid laudantium.", "Sequi ullam recusandae unde." },
                    { 105, 2, new DateTime(2019, 4, 11, 3, 41, 51, 118, DateTimeKind.Local), null, false, "Fugiat porro incidunt earum quaerat nostrum necessitatibus aliquid omnis.", "Doloribus minus natus ex blanditiis nisi sit numquam. Accusamus similique qui in. Esse sit architecto quibusdam blanditiis doloremque. Porro iure est rerum tempora ea et et voluptatem. Temporibus molestias aut similique dolor vel odit. Impedit cupiditate aut debitis qui facilis culpa. Autem laboriosam quibusdam non repudiandae occaecati provident vel enim.", "Animi at labore quis." },
                    { 1, 2, new DateTime(2019, 4, 10, 3, 41, 50, 985, DateTimeKind.Local), null, false, "Ut quia nihil fugiat et doloremque sed eum.", "At laboriosam tenetur eius aut consequatur corrupti illum. Debitis voluptatem voluptates est non debitis. Excepturi ipsum consectetur magnam maiores. Quam molestiae sit enim. Sunt facere et quis minus doloremque debitis id quas. Non earum eum quae natus quidem et repellendus sint. Id voluptas iure magni.", "Qui et nisi molestias esse." },
                    { 104, 1, new DateTime(2019, 4, 7, 3, 41, 51, 117, DateTimeKind.Local), null, true, "Praesentium doloribus illo nihil voluptatem accusantium mollitia numquam nemo.", "Iusto commodi qui magnam consequatur blanditiis quis fuga. Voluptas adipisci animi error eos est optio perspiciatis aut. Omnis beatae sed illum et atque exercitationem est. Porro et corporis quia perspiciatis vero sed optio. Sit et nemo reiciendis. Iste provident temporibus excepturi minus. Quod maiores itaque hic placeat velit cum ut perspiciatis. Voluptas quasi minus iste voluptates.", "Quibusdam facere reiciendis veniam quo aut." },
                    { 96, 1, new DateTime(2019, 4, 10, 3, 41, 51, 110, DateTimeKind.Local), null, true, "Repellat quod voluptates beatae voluptate voluptas quasi.", "Est quisquam molestiae veritatis est aut voluptatum earum praesentium. Assumenda ea explicabo minus similique. Commodi quos delectus assumenda. Asperiores aut maiores et deserunt. Optio sed aut non labore. Ad cupiditate doloribus culpa accusantium nulla. Reiciendis eum ea delectus tempore.", "Deserunt eligendi laborum earum harum illo tempore." },
                    { 88, 1, new DateTime(2019, 4, 8, 3, 41, 51, 102, DateTimeKind.Local), null, true, "Facere quae et quia omnis ut soluta molestiae.", "Dolores neque omnis ea iusto culpa. Consequatur impedit necessitatibus a sed. Dolores officiis quaerat quos explicabo. Quis consequatur ad nihil quia omnis odit. Magnam adipisci sed aut quisquam occaecati ipsam laboriosam. Odit voluptatem ipsum nobis praesentium at. Fugit iste sit occaecati et repellat assumenda. Blanditiis autem eum est eos praesentium iusto culpa.", "Non sequi rem." },
                    { 80, 1, new DateTime(2019, 4, 11, 3, 41, 51, 94, DateTimeKind.Local), null, true, "Quia eius quas laboriosam laudantium aut accusamus.", "Molestiae aut recusandae corporis maiores. Harum enim cumque est aperiam cupiditate dignissimos. Quidem quo ut est. Voluptatem et illum ut quia itaque et. Dolorem ipsum hic vel ducimus quibusdam eum ex. Magni aperiam quam neque sint. Harum eveniet voluptas atque qui et provident.", "Commodi ea debitis totam eos facere tempora." },
                    { 72, 1, new DateTime(2019, 4, 9, 3, 41, 51, 84, DateTimeKind.Local), null, true, "Eaque voluptate vitae commodi necessitatibus non omnis aut.", "Doloremque minima id enim odit. Aut quaerat possimus est. Natus quae ad et. Totam architecto voluptatem suscipit quia. Iure non quos ullam qui aut quisquam. Repudiandae minus illum voluptas rem alias qui rerum dolores. Rerum eum ipsam voluptas veniam. Eveniet at aliquam quia provident.", "Modi sed nulla eligendi voluptate quod veniam." },
                    { 64, 1, new DateTime(2019, 4, 7, 3, 41, 51, 78, DateTimeKind.Local), null, true, "Debitis quisquam consequatur ab sed ipsum magni totam eveniet.", "Sit et quo quia iste. Dignissimos aut doloribus omnis. Voluptatibus aut blanditiis fugit. Quam alias voluptas ut accusantium aliquam. Dolores reiciendis nulla et ipsam vitae nisi. Voluptatum autem nihil possimus ut accusantium.", "Sit asperiores quo voluptatem non quo." },
                    { 56, 1, new DateTime(2019, 4, 10, 3, 41, 51, 70, DateTimeKind.Local), null, true, "Quia necessitatibus inventore tempora qui minima sint est eos perspiciatis.", "Ullam cumque modi alias. Corrupti eligendi non voluptatibus. Nesciunt qui qui voluptatem. Quis placeat ipsam voluptas libero nesciunt. Iste sit deleniti expedita rerum quis voluptatem molestiae. Nihil nemo tempora suscipit ad maxime doloremque libero qui. Aut quos laborum voluptates dicta eligendi temporibus voluptas autem. Quia at consequuntur voluptatibus atque qui saepe occaecati vel.", "Est quod dolorem ad quia earum quam." },
                    { 48, 1, new DateTime(2019, 4, 8, 3, 41, 51, 64, DateTimeKind.Local), null, true, "Nemo qui aut culpa quisquam dolor voluptatibus ut eum hic.", "Ad et quisquam quia dolorum voluptas suscipit est. Provident id occaecati a sit commodi dolore labore quia. Vitae quisquam consectetur quis non. Eum sed dolores dolorem. Rerum ratione consectetur omnis nemo animi ut libero. Ipsam asperiores repellendus laborum.", "Vitae molestiae excepturi." },
                    { 40, 1, new DateTime(2019, 4, 11, 3, 41, 51, 57, DateTimeKind.Local), null, true, "Eligendi quidem sit est ut et impedit ipsum.", "Ut assumenda possimus dolore quasi aliquid optio. Nemo doloribus eos consequatur sapiente tempora hic explicabo. Voluptas ut voluptates labore amet est nam. Consectetur fugit perferendis quis laborum ex soluta omnis optio. Labore et autem eligendi quas vitae corrupti. Porro officia reprehenderit soluta animi molestias eaque quasi eum. Officia consequatur quae ipsa sunt laboriosam debitis ut soluta.", "Ratione in eum placeat." },
                    { 32, 1, new DateTime(2019, 4, 9, 3, 41, 51, 50, DateTimeKind.Local), null, true, "Molestiae ipsa non enim aut id est ratione praesentium vero qui iste.", "Sunt repellat eos mollitia dolor unde eum illo. Dignissimos voluptates sit earum. Debitis ut error voluptas eius expedita. Totam qui corrupti ducimus quia est. Et fugiat placeat quam a necessitatibus. Provident dolorem dolore tenetur quas. Sequi vel velit non voluptatem similique non et maxime.", "Optio quos tempora illo." },
                    { 24, 1, new DateTime(2019, 4, 7, 3, 41, 51, 42, DateTimeKind.Local), null, true, "Suscipit eveniet perferendis accusamus dicta soluta voluptas.", "Numquam quia fugit temporibus et. Praesentium asperiores est dolores quasi molestiae asperiores. Alias quas doloremque voluptatibus aut. Omnis voluptatem et accusantium molestiae sit perspiciatis accusantium. Ut nobis facere dolorem. Quod laboriosam possimus provident rerum. Quo ullam voluptate in.", "Omnis omnis adipisci rem." },
                    { 16, 1, new DateTime(2019, 4, 10, 3, 41, 51, 36, DateTimeKind.Local), null, true, "Nulla nobis nulla velit aut ratione facilis sint asperiores quas officiis cumque.", "Molestias cumque iste rerum sit. Quia deleniti enim enim. Vitae molestias provident enim dicta. Quis laudantium sequi qui repellat aspernatur iure. Iste ducimus modi magni. Quis esse fuga qui sed assumenda.", "Qui ut omnis aut temporibus." },
                    { 112, 1, new DateTime(2019, 4, 9, 3, 41, 51, 123, DateTimeKind.Local), null, true, "Quisquam sint dolor molestiae dolores aut odio corrupti reprehenderit sunt et commodi.", "Sed distinctio molestiae iusto aut qui id. Dolore voluptatem nemo doloremque est labore voluptatibus modi sed. Voluptatum qui fuga maiores at atque hic. Nemo vel dolorum non et sequi temporibus. Numquam et maiores ea est assumenda consectetur. Optio qui officia fugiat non libero cumque mollitia.", "Quidem sequi labore voluptatem accusantium inventore ut." },
                    { 115, 4, new DateTime(2019, 4, 11, 3, 41, 51, 125, DateTimeKind.Local), null, false, "Laborum soluta rerum alias voluptatum adipisci molestiae voluptatem recusandae deleniti quibusdam.", "Nesciunt culpa libero tenetur tenetur. Cumque mollitia repellat porro dolor delectus nostrum. Quibusdam neque autem repellat. Amet consequatur ullam sunt voluptatem. Quam explicabo mollitia tempora id vel. Molestiae iure laborum non nobis nobis.", "Reiciendis labore sunt nemo." },
                    { 113, 2, new DateTime(2019, 4, 8, 3, 41, 51, 123, DateTimeKind.Local), null, false, "Harum blanditiis earum earum eligendi numquam iste doloremque commodi perspiciatis.", "Impedit harum ut nostrum consequuntur saepe sed et rerum. Accusantium fuga et rerum. Eligendi vitae fugit perspiciatis sint ullam cum. Ea reiciendis sunt iusto deserunt. Facilis facilis ea est et aut unde accusantium. Soluta unde quis id qui vel suscipit explicabo qui.", "Aperiam praesentium cupiditate officiis." },
                    { 10, 3, new DateTime(2019, 4, 11, 3, 41, 51, 31, DateTimeKind.Local), null, false, "Aut voluptatem itaque voluptates distinctio nihil ut unde.", "Eos veritatis debitis enim at. Qui fuga voluptas ipsum natus rerum cum debitis. Laborum facere distinctio quia adipisci architecto. Enim maiores aut aliquam voluptas quidem temporibus sunt natus. Praesentium sed error fugiat deserunt. Et soluta rerum animi.", "Modi aut velit dolor." },
                    { 99, 4, new DateTime(2019, 4, 7, 3, 41, 51, 113, DateTimeKind.Local), null, false, "Aperiam rem doloribus harum dolor qui at et accusantium voluptas rem.", "Et laboriosam id dignissimos hic omnis consectetur exercitationem. Libero ducimus est ex dolore accusamus. Natus voluptas aut corporis placeat non a vel et. Beatae velit nam non eius deserunt molestiae sit et. Iste sequi laboriosam exercitationem harum modi. Quisquam fugit hic est dolores. Et enim deleniti at aspernatur aperiam sunt eum autem.", "Ea quas qui libero." },
                    { 91, 4, new DateTime(2019, 4, 10, 3, 41, 51, 105, DateTimeKind.Local), null, false, "Velit ratione voluptas tempore veniam aut aliquam et.", "Sed ut et numquam. Placeat est voluptate voluptatem consequatur culpa illum nam. Fugiat delectus id doloremque in quia. Sunt non dolores eum maiores voluptas sit delectus. Sapiente veritatis et impedit voluptatem suscipit maxime. Itaque illum eos reiciendis nulla laboriosam laborum possimus consequuntur.", "Sed eum est." },
                    { 83, 4, new DateTime(2019, 4, 8, 3, 41, 51, 97, DateTimeKind.Local), null, false, "Delectus a culpa voluptatum quas eaque officia enim consectetur ad quia expedita.", "Iste ut inventore corporis corporis dolore nam facere. Consequuntur et voluptas omnis impedit tenetur est cum. Ad temporibus possimus maiores tempora eum. Dignissimos minima nihil quia dolore dolorum qui aliquam laudantium. Cum et voluptatem eos aspernatur voluptate quod. Error dolore animi doloribus est ad. Quo aut molestiae sit. Similique eaque incidunt nihil.", "Quia eum sit quos nam qui." },
                    { 75, 4, new DateTime(2019, 4, 11, 3, 41, 51, 87, DateTimeKind.Local), null, false, "Deserunt rerum ut rerum unde ut ut sunt ipsum qui amet.", "Et harum autem cum sit ea aut. Ipsum blanditiis deleniti qui et rem quisquam deserunt facilis. Perferendis cumque quia nihil dicta rem nihil non. Occaecati dolor nam facilis eligendi. Sunt ad ea et. Iusto est veniam deserunt eius quos. Aut laboriosam cum distinctio quas est.", "Consequatur temporibus ex eos adipisci commodi." },
                    { 67, 4, new DateTime(2019, 4, 9, 3, 41, 51, 80, DateTimeKind.Local), null, false, "Mollitia quis vel eos eius cum illum dolor quibusdam explicabo.", "Tempora ut id inventore. Velit expedita deleniti dolor perspiciatis ea. Sapiente officiis natus nam accusamus tenetur laudantium. Minus accusantium perferendis consequatur. Dicta suscipit iusto aut commodi consequatur error molestias. Repellendus in adipisci laborum repudiandae beatae. Distinctio nemo at quo nemo nemo magnam aut. Illum quos qui necessitatibus vel sed.", "Sunt nesciunt rem quaerat eaque eum." },
                    { 59, 4, new DateTime(2019, 4, 7, 3, 41, 51, 74, DateTimeKind.Local), null, false, "Similique autem tempore aut nihil reiciendis et laboriosam et.", "Provident suscipit sit quisquam autem odio aut. Quisquam magnam fugit omnis iure explicabo vel explicabo. Iste laudantium et dolorem sapiente a nisi impedit. Praesentium ipsum quos et veritatis dolorem. Voluptas rem nesciunt sapiente reprehenderit voluptatem. Ut saepe facilis tempore expedita neque non ipsam. Inventore fugiat velit voluptates qui.", "Hic velit dolorum fuga." },
                    { 51, 4, new DateTime(2019, 4, 10, 3, 41, 51, 66, DateTimeKind.Local), null, false, "Fugit minus est provident veniam laborum est enim quidem provident.", "Ullam magni aut minima. Quaerat vero alias et. Fugiat alias veritatis ut et dolores atque. Aut et non sit qui et placeat. Facilis dolore eligendi molestiae aut dignissimos non distinctio omnis. Rerum laborum distinctio similique in ea eum modi. Et cupiditate reprehenderit in. Rerum ut eum aliquam.", "Rem ea corrupti fugit at." },
                    { 43, 4, new DateTime(2019, 4, 8, 3, 41, 51, 59, DateTimeKind.Local), null, false, "Voluptas libero rerum et nostrum et soluta odit non sunt et.", "Sit magnam iure hic repellat cumque aut eum. Porro architecto officia harum. Est reprehenderit inventore omnis molestiae dicta totam non. Dolorum minima illo fugiat porro dolor ducimus. Qui sit alias illo quis consequatur praesentium. Voluptas eum tenetur sapiente itaque id voluptatum voluptas iusto. Aut optio quia et voluptate et ea.", "Minima accusantium mollitia id aspernatur aliquam." },
                    { 35, 4, new DateTime(2019, 4, 11, 3, 41, 51, 52, DateTimeKind.Local), null, false, "Quia dolorem sunt qui vel sunt ut consequatur officiis suscipit.", "Cupiditate saepe doloribus iste. Aperiam sequi voluptatem occaecati a nesciunt ea quibusdam. Nisi beatae et qui veniam voluptatem a et architecto. Totam quaerat modi veniam illum. Maiores rem omnis magni voluptate in sunt neque quia. Ipsam quo temporibus voluptas. Quaerat enim totam blanditiis expedita explicabo soluta.", "Ut nobis et nam dolores earum." },
                    { 27, 4, new DateTime(2019, 4, 9, 3, 41, 51, 45, DateTimeKind.Local), null, false, "Vero rerum architecto dolorum quaerat iste ea amet dignissimos aut.", "Non ducimus cum in excepturi assumenda. Reprehenderit minus voluptate maiores cum. Et sed excepturi quasi. Autem tempora soluta minima libero non. Voluptatum aperiam occaecati et accusantium. Quod consequatur sed quibusdam.", "Natus facilis odio." },
                    { 19, 4, new DateTime(2019, 4, 7, 3, 41, 51, 38, DateTimeKind.Local), null, false, "Voluptatem modi ex nihil ut quod voluptas.", "Dolor illum culpa qui sunt enim nemo nihil. Laborum qui quis voluptate modi sapiente sed. Eum quia et corrupti iste praesentium debitis debitis. Et voluptas placeat deleniti odio aperiam voluptas ratione. Ipsam quis iusto dolore repellendus. Sequi a unde ut provident non. Enim architecto explicabo rerum et.", "Tempore qui ipsum quam cupiditate quaerat itaque est." },
                    { 11, 4, new DateTime(2019, 4, 10, 3, 41, 51, 31, DateTimeKind.Local), null, false, "Voluptatem eligendi aliquam voluptates recusandae impedit magni nesciunt quo et.", "Non mollitia earum quas fugiat placeat est magnam nihil. Ipsam quidem voluptatem et nesciunt facilis enim. Libero et est dolorem ut sit. Dolore ut quis dicta expedita sint iure vitae cumque. Et id vel voluptas ut enim aut excepturi aliquid. Quasi sint non aut in quos. Molestias voluptatem neque ipsa dolore omnis in officia. Voluptatem neque assumenda rerum non.", "Quo eos qui laborum quia molestias neque amet." },
                    { 2, 3, new DateTime(2019, 4, 9, 3, 41, 51, 11, DateTimeKind.Local), null, false, "Nam sed alias omnis non explicabo veritatis assumenda veritatis.", "Est autem nostrum maiores incidunt ea sed nihil. Maiores eos aut incidunt neque voluptas. Itaque dicta consectetur impedit quia est. Recusandae quia aut ea et dolores nostrum. Consequatur eaque enim magni reprehenderit aspernatur qui inventore sit. Minima dignissimos recusandae necessitatibus. Animi nemo et cumque. Nihil tempora dolorem iste fugiat autem.", "Aperiam itaque ut autem accusantium aut officia eveniet." },
                    { 3, 4, new DateTime(2019, 4, 8, 3, 41, 51, 12, DateTimeKind.Local), null, false, "Dicta eum voluptatem perspiciatis reiciendis est et amet.", "Ipsa modi excepturi illo qui autem aut. Qui accusamus possimus ullam mollitia id deleniti. Dolor similique aliquid aliquid officiis quia eaque soluta enim. Iusto laborum qui numquam. Distinctio quas ratione ipsam odio est rerum. Dolores non iste et consectetur neque id laboriosam non.", "Dolor blanditiis ea enim odit molestiae nostrum." },
                    { 106, 3, new DateTime(2019, 4, 10, 3, 41, 51, 119, DateTimeKind.Local), null, false, "Et fuga at minima numquam nihil itaque et atque cumque aut a.", "Maxime molestias eos voluptas expedita. Veritatis veniam accusantium qui. Ab id enim aut. Exercitationem fugiat reiciendis iure. Voluptas voluptatem excepturi maiores vel. Ex nisi cupiditate aut molestiae dolore facilis est accusantium. Et est facere et rerum sint cum dolorem. Maxime quas dolore odio iste ea reprehenderit in delectus.", "Hic corrupti eos ratione modi id." },
                    { 98, 3, new DateTime(2019, 4, 8, 3, 41, 51, 112, DateTimeKind.Local), null, false, "Nulla qui sint cum iure natus cum ipsa.", "Blanditiis praesentium non ab. Nobis reiciendis est voluptates aut quia suscipit totam. Est ab totam repellendus id. Nesciunt dolores est consequuntur. Quia ut quis sit a. Recusandae ipsa beatae sed voluptas voluptas. Sed id nesciunt animi.", "Minus vel accusamus voluptatem minus." },
                    { 90, 3, new DateTime(2019, 4, 11, 3, 41, 51, 104, DateTimeKind.Local), null, false, "Similique rem iure aut nisi consectetur in autem facilis aperiam.", "Magni quis ducimus officiis voluptatibus perferendis est laborum. Suscipit quod iusto perferendis vel. Asperiores dolore aut velit corporis dolorum atque quisquam aut. Officiis tempore dolores eaque et eligendi. Quia hic cum qui soluta consectetur soluta officiis. Ea omnis ut commodi architecto est nam sint. Voluptas modi officiis ea numquam.", "Et nihil vero." },
                    { 82, 3, new DateTime(2019, 4, 9, 3, 41, 51, 96, DateTimeKind.Local), null, false, "Quos quia dolorem ut quasi dolores eius est soluta dignissimos voluptas et.", "Quibusdam non magni repellendus excepturi odit quia. Ipsa omnis sit similique dolorum sint a animi. Atque enim provident quasi aperiam dolor ut. Repellat culpa dolorum vero. Quia sint molestias voluptatem non. Itaque vero omnis ratione aspernatur tempora aliquam architecto.", "Nobis excepturi cupiditate cumque." },
                    { 74, 3, new DateTime(2019, 4, 7, 3, 41, 51, 86, DateTimeKind.Local), null, false, "Doloribus accusantium fugit blanditiis dicta aliquam iste reprehenderit hic.", "Et ullam alias officia neque consequuntur aut. Quidem eius expedita quo dolorem quia. Dolores in mollitia et et provident consequatur sapiente. Quo consequuntur aut quo. Voluptatum aut nam nobis quo porro cumque. Voluptas quia nihil omnis velit mollitia vel quo dolorum. Minima aut a aut vel aperiam enim eaque. Laboriosam et officiis aperiam dolore ullam maxime neque.", "Sit est voluptatem eum explicabo consequatur animi est." },
                    { 66, 3, new DateTime(2019, 4, 10, 3, 41, 51, 79, DateTimeKind.Local), null, false, "Corrupti qui quasi voluptates enim consequuntur odio.", "Esse velit itaque sit in porro. Minima repellat et perferendis rerum et incidunt omnis. Omnis maiores id tenetur. Quod qui distinctio sed iusto incidunt ea non. Provident rerum quas laudantium. Sit quod sunt officiis excepturi velit beatae. Ex laudantium debitis tenetur ab vel pariatur corrupti. Aut earum quibusdam tempore vel minima atque.", "Est ducimus veniam." },
                    { 58, 3, new DateTime(2019, 4, 8, 3, 41, 51, 73, DateTimeKind.Local), null, false, "Aut magnam non est consequatur molestiae assumenda.", "Eos quo aut quaerat amet natus doloremque sed. Asperiores molestiae ut est excepturi perspiciatis. Voluptas nihil dicta ut rem. Eius magni ratione architecto nemo illum deleniti quae et. Unde minus aspernatur accusamus architecto et libero. Impedit saepe voluptas rerum fugit molestiae veniam accusamus. Est voluptas vel ut asperiores ut alias quos reiciendis.", "Repudiandae velit tempore sequi cupiditate facere quis." },
                    { 50, 3, new DateTime(2019, 4, 11, 3, 41, 51, 65, DateTimeKind.Local), null, false, "Placeat saepe temporibus dolorem quaerat ea saepe et sint et qui expedita.", "Minima nulla ut eum libero. Excepturi quam praesentium sed molestiae repellat consequuntur accusamus. Voluptatem aut molestias ab autem reprehenderit. Tenetur iste natus voluptate voluptatem et omnis. Veniam nulla nisi qui dolore autem aliquid. Possimus non beatae voluptatem quam tempore et ullam. Ipsam unde voluptates impedit minima dolor architecto.", "Fuga quia quibusdam ut." },
                    { 42, 3, new DateTime(2019, 4, 9, 3, 41, 51, 59, DateTimeKind.Local), null, false, "Velit rerum doloremque quo repellendus dicta expedita consequatur veritatis rem dolores.", "Eligendi id adipisci esse quo optio. Illum eius dignissimos unde. Modi consequuntur quam a ut. Illum nostrum cupiditate nam eveniet velit. Illo rerum aut nisi dicta. Ratione rem dolores blanditiis molestiae. Sit tempora et nisi cupiditate. Necessitatibus culpa sed laboriosam vel excepturi quo iure dolorum.", "In possimus est libero." },
                    { 34, 3, new DateTime(2019, 4, 7, 3, 41, 51, 52, DateTimeKind.Local), null, false, "Totam doloribus enim quisquam possimus nam et.", "Est non est sed et. Impedit esse beatae totam nihil. Eum quidem neque occaecati. Vel temporibus rerum maxime quibusdam itaque. Quia mollitia vitae iste. Sed enim corporis aliquam non exercitationem vitae quisquam aut.", "Quibusdam id eveniet magni quo." },
                    { 26, 3, new DateTime(2019, 4, 10, 3, 41, 51, 44, DateTimeKind.Local), null, false, "Nisi officia iure voluptatum hic eos mollitia molestiae natus dolor.", "Temporibus beatae eum recusandae facere corrupti consequatur repellat corporis. At doloremque voluptatibus hic. Aperiam consectetur neque neque repudiandae ut et atque. Autem in consequuntur harum quae esse. Sit cumque et quam. Ex autem et qui optio. Sint beatae esse optio rem voluptas aspernatur.", "Dolor hic necessitatibus ab tempore." },
                    { 18, 3, new DateTime(2019, 4, 8, 3, 41, 51, 37, DateTimeKind.Local), null, false, "Illum inventore repellendus in culpa nesciunt quam qui suscipit laudantium.", "Ut autem ea eligendi totam qui quo. Error maxime esse iste tempora optio commodi deleniti ut. Excepturi quidem possimus consequatur perferendis vitae tempora. Ab illum sint iusto debitis voluptas id ipsum. Repellendus eveniet architecto aut est corporis nostrum explicabo ea. Sed sit esse et eos. Exercitationem optio dolorem eveniet animi ea minima. Expedita in eveniet et magni accusamus.", "Laborum quibusdam accusantium fuga." },
                    { 114, 3, new DateTime(2019, 4, 7, 3, 41, 51, 124, DateTimeKind.Local), null, false, "Nihil cumque est aut ex quidem tempore ut eum ut repellat adipisci.", "Libero pariatur ipsa fugiat inventore libero. Iusto repellat unde error tempora. Voluptatem aut commodi sint a voluptas. Cumque libero iste nemo est amet deleniti provident. Dicta nulla eos blanditiis ut libero dolore. Soluta in repellendus nihil molestias eligendi libero asperiores. Voluptates occaecati et tempore ut similique unde exercitationem. Repellat nostrum minus veritatis officiis consectetur impedit temporibus.", "Necessitatibus ipsam ut ad sapiente aut aut perspiciatis." },
                    { 119, 8, new DateTime(2019, 4, 7, 3, 41, 51, 128, DateTimeKind.Local), null, false, "Beatae quia omnis vel velit at possimus labore voluptas facilis est.", "Ea reprehenderit sed ea et totam quisquam ratione. Aut ipsa rerum corrupti molestiae dolorem. Molestias sit perspiciatis molestiae atque error maxime. Dicta deserunt quo et pariatur itaque vel. Dolore accusantium facere corporis tempora. Impedit odit dolore iusto veniam quis in necessitatibus.", "Enim harum modi exercitationem." }
                });

            migrationBuilder.CreateIndex(
                name: "IX_News_CategoryId",
                table: "News",
                column: "CategoryId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "News");

            migrationBuilder.DropTable(
                name: "Categories");
        }
    }
}
